/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-04-29 05:01:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.biz;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class weeklySubjectRgst_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Source/IT_Biz/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITBiz/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1615536694853L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.3.jar", Long.valueOf(1615538384558L));
    _jspx_dependants.put("jar:file:/D:/Source/IT_Biz/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITBiz/WEB-INF/lib/spring-webmvc-5.3.3.jar!/META-INF/spring-form.tld", Long.valueOf(1610400454000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>IT Working List</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Custom fonts for this template-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("vendor/fontawesome-free/css/all.min.css\"\r\n");
      out.write("\t\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link\r\n");
      out.write("\t\thref=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("\t\trel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Custom styles for this template-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("js/jquery.tablesorter.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page level plugins -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page level custom scripts -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("js/demo/chart-pie-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tth {\r\n");
      out.write("\t\t\tposition: sticky;\r\n");
      out.write("\t\t\ttop: 0px;\r\n");
      out.write("\t\t\tbox-shadow: 0 1px 1px -1px rgba(0, 0, 0, 0.4);\r\n");
      out.write("\t\t\tbackground-color: #F6F6F6;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttbody tr td {\r\n");
      out.write("\t\t\tpadding: 0.3rem !important;\r\n");
      out.write("\t\t\tz-index: 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttbody tr {\r\n");
      out.write("\t\t\theight:30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttbody tr:hover {\r\n");
      out.write("\t\t\tbackground-color: #CCF6F6;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttbody tr.active {\r\n");
      out.write("\t\t\tbackground-color: #E8F6F6;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.clicked {\r\n");
      out.write("\t\t\tbackground-color: #E8F6F6;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.trstyle {\r\n");
      out.write("\t\t\tpadding: 0.3rem !important;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\t<!-- Page Wrapper -->\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Content Wrapper -->\r\n");
      out.write("\t\t<!-- Content Wrapper -->\r\n");
      out.write("\t\t<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main Content -->\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 화면 이름 아이콘 & 이름 -->\r\n");
      out.write("\t\t\t\t<div class=\"col-auto\" style=\"margin-left: 20px\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"h4 mb-0 text-gray-800\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"display: inline; margin-left: 10px\">Category 관리</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle='margin-top: 20px; width: 100%; height: calc(100% - 149px);'>\r\n");
      out.write("\t\t\t\t\t<!-- 타이틀 및 버튼부 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card border-left-primary shadow h-0 py-0\"\r\n");
      out.write("\t\t\t\t\t\tstyle='height: 60px; width: calc(100% - 20px); margin-left: 10px;'>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\" style='height: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row no-gutters align-items-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-left: -20px; margin-top: -20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-auto\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle='margin-left: 20px; margin-top: 12px'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fas fa-calendar fa-2x text-gray-300\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col mr-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"text-xs font-weight-bold text-primary text-uppercase mb-0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle='margin-left: 15px; margin-top: 14px; font-size: 14px; width: 100%'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid='div_left_search_header'>Category List</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style='margin-top: 8px;'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary btn-icon-split\" id=\"btn_add\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"icon text-white-50\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-bolt rotate-15\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <span class=\"text\">Add</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"btn btn-success btn-icon-split\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"btn_save\" style='margin-left: 5px'> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon text-white-50\"> <i class=\"fas fa-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <span class=\"text\">Save</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"btn btn-danger btn-icon-split\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"btn_delete\" style='margin-left: 5px'> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon text-white-50\"> <i class=\"fas fa-trash\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span> <span class=\"text\">Delete</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Category Table List 부 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card shadow mb-4\"\r\n");
      out.write("\t\t\t\t\t\tstyle='margin-top: 10px; margin-left: 10px; width: calc(100% - 20px); height: calc(100% - 80px)'>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle='height: 570px; border: 1px solid #DEDEDE'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"tablesorter table table-bordered\" id=\"categoryDataTable\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle='width: 60px; padding: 0.5rem !important; text-align: center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-flag\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle='width: 80px; padding: 0.5rem !important; text-align: center'>Seq.</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle='width: 450px; padding: 0.5rem !important; text-align: center'>Subject</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle='width: 600px; padding: 0.5rem !important; text-align: center'>비\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t고</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle='width: 100px; padding: 0.5rem !important; text-align: center'>사용\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t유무</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style='padding: 0.5rem !important; text-align: center'>정렬\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t순서</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End of Main Content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t<footer class=\"sticky-footer bg-white\">\r\n");
      out.write("\t\t\t\t<div class=\"container my-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyright text-center my-auto\">\r\n");
      out.write("\t\t\t\t\t\t<span>Copyright &copy; IT Team Biz work 2021</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t<!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- End of Content Wrapper -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Scroll to Top Button-->\r\n");
      out.write("\t\t<a class=\"scroll-to-top rounded\" href=\"#page-top\"> <i\r\n");
      out.write("\t\t\tclass=\"fas fa-angle-up\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"InfoModal\" tabindex=\"-1\"\r\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" style='width: 900px'>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"info_Title\"></h5>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">×</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" id=\"info_Body\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\" id=\"btn_info_yes\" onclick=\"changeFlag('D')\">Yes</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\">No</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"SaveInfoModal\" tabindex=\"-1\"\r\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" style='width: 900px'>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"save_info_Title\"></h5>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">×</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" id=\"save_info_Body\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\">OK</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"SaveCheckModal\" tabindex=\"-1\"\r\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\" style='width: 900px'>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"save_check_Title\"></h5>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">×</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" id=\"save_check_Body\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\" id=\"btn_savecheck_yes\">Yes</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-dismiss=\"modal\">No</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type='text/javascript'>\r\n");
      out.write("\t\t// Flag Icon 변경\r\n");
      out.write("\t\tvar target_row;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction changeFlag(rowstatus) {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t추가 : fas fa-plus\r\n");
      out.write("\t\t\t일반 : fas fa-caret-right\r\n");
      out.write("\t\t\t삭제 : fas fa-cut\r\n");
      out.write("\t\t\t업데이트 : fas fa-pen\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\tif (!target_row) {return;}\r\n");
      out.write("\t\t\tswitch (rowstatus) {\r\n");
      out.write("\t\t\t\tcase 'U':\r\n");
      out.write("\t\t\t\t\tvar now_status = $('#table_font_' + target_row).attr('class');\r\n");
      out.write("\t\t\t\t\tif (now_status != 'fas fa-plus') {\r\n");
      out.write("\t\t\t\t\t\t$('#table_font_' + target_row).attr('class', 'fas fa-pen');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'I':\r\n");
      out.write("\t\t\t\t\t$('#table_font_' + target_row).attr('class', 'fas fa-plus');\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 'R':\r\n");
      out.write("\t\t\t\t\t$('#table_font_' + target_row).attr('class', 'fas fa-caret-right');\r\n");
      out.write("\t\t\t\t\tbreak\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tcase 'D':\r\n");
      out.write("\t\t\t\t\t$('#table_font_' + target_row).attr('class', 'fas fa-cut');\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tdefault:\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t// Category 불러오기\r\n");
      out.write("\t\t\t//$(\"#categoryDataTable\").tablesorter();\r\n");
      out.write("\t\t\t$.tablesorter.addParser({\r\n");
      out.write("\t\t\t\tid:\"input_text\",\r\n");
      out.write("\t\t\t\tis:function() {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tformat: function( s, table, cell) {\r\n");
      out.write("\t\t\t        return $(\"input\", cell).val();\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    type: 'text'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.tablesorter.addParser({\r\n");
      out.write("\t\t\t\tid:\"checkbox\",\r\n");
      out.write("\t\t\t\tis:function() {\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tformat: function( s, table, cell) {\r\n");
      out.write("\t\t\t        return $(\"input\", cell).val();\r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    type: 'text'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsearchAllSubject();\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tfunction searchAllSubject() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//$(\"#categoryDataTable\").empty();\r\n");
      out.write("\t\t\t\t//$(\"#categoryDataTable > tbody\").html(\"\");\r\n");
      out.write("\t\t\t\t// 원래 하던거 $(\"#categoryDataTable\").find(\"tr:gt(0)\").remove();\r\n");
      out.write("\t\t\t\t//$('#categoryDataTable').find('tbody').empty();\r\n");
      out.write("\t\t\t\t//$('#categoryDataTable tbody').empty();\r\n");
      out.write("\t\t\t\t//$('#categoryDataTable tbody').remove();\r\n");
      out.write("\t\t\t\t//$('#categoryDataTable tr').eq(1).remove();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#categoryDataTable tbody').remove();\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("biz/searchAllSubjectList',\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\t\t\t//alert(JSON.stringify(result))\r\n");
      out.write("\t\t\t\t\t\t\t\tif (result.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tbody = $('<tbody>');\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\tfor (i = 0; i < result.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar row = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'<tr id=\"rowid_' + i + '\">')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.addClass('trstyle');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell0 = $('<td style=\"text-align:center\"><i class=\"fas fa-caret-right\" id=\"table_font_' + i + '\"></i>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell1 = $('<td style=\"text-align:center\" id=\"bws_seq_' + i + '\">').text(result[i].bws_seq)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell2 = $('<td><input type=\"text\" class=\"data_text\" id=\"bws_content_'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '\" value=\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ result[i].bws_content\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '\" style=\"width:100%; border:none\">')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell3 = $('<td><input class=\"data_text\" type=\"text\" id=\"bws_remark_'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '\" value=\"'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ result[i].remark\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '\" style=\"width:100%;border:none\">')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell4;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//잘됨\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/* if (result[i].use_yn == 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcell4 = $('<td><input type=\"checkbox\" id=\"use_yn_' + i + '\" value=\"' + result[i].use_yn + '\" checked>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcell4 = $('<td><input type=\"checkbox\" id=\"use_yn_' + i + '\" value=\"' + result[i].use_yn + '\">')\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/* <p class=\"onoff\"><input type=\"checkbox\" value=\"1\" id=\"checkboxID\"><label for=\"checkboxID\"></label></p> */\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/* cell4 = $('<p class=\"onoff\" style=\"margin-left:18px;margin-top:6px\"><input type=\"checkbox\" value=\"1\" id=\"use_yn_' + i + '\"><label for=\"checkboxID\"></label></p>') */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// 여러개는 나오는데 체크하면 최 상단 하나만 정상 작동함. 그리고 input의 id 변경(checkboxID)하면 작동 자체가 안됨\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (result[i].use_yn == 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//cell4 = $('<p class=\"onoff\" style=\"margin-left:18px;margin-top:2px;height:20px ;\"><input type=\"checkbox\" value=\"Y\" id=\"checkboxID_' + i + '\" checked><label for=\"checkboxID_' + i + '\" style=\"height:30px\"></label></p>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//cell4 = $('<td><p class=\"onoff\" style=\"margin-left:18px;margin-top:2px;height:20px ;\"><input type=\"checkbox\" value=\"Y\" id=\"checkboxID_' + i + '\" checked><label for=\"checkboxID_' + i + '\" style=\"height:30px\"></label></p></td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcell4 = $('<td class=\"data_text\" style=\"text-align:center\"><input type=\"checkbox\" value=\"Y\" class=\"data_checkbox\" id=\"checkboxID_' + i + '\" checked></td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//cell4 = $('<td><p class=\"onoff\" style=\"margin-left:18px;margin-top:2px;height:20px ;\"><input type=\"checkbox\" value=\"N\" id=\"checkboxID_' + i + '\"><label for=\"checkboxID_' + i + '\" style=\"height:30px\"></label></p></td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcell4 = $('<td style=\"text-align:center\"><input type=\"checkbox\" class=\"data_checkbox\" value=\"N\" id=\"checkboxID_' + i + '\"></td>')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//var cell5 = $('<td class=\"data_text\">').text(result[i].sort_no);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar cell5 = $('<td><input type=\"text\" class=\"data_text\" id=\"sort_no_' + i + '\" value=\"'\t+ result[i].sort_no + '\" style=\"width:100%; border:none\">')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//alert(row)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(row).append(cell0, cell1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcell2, cell3,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcell4, cell5);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(tbody).append(row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//$(\"#categoryDataTable > tbody\").append(row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#categoryDataTable\").append(tbody);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#categoryDataTable\").trigger('update')\r\n");
      out.write("\t\t\t\t\t\t\t\tcategorytablesort();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcategorytablesort = function() {\r\n");
      out.write("\t\t\t\t$('#categoryDataTable').tablesorter({\r\n");
      out.write("\t\t\t\t\theaders: {\r\n");
      out.write("\t\t\t\t\t\t2 : {sorter : 'input_text'},\r\n");
      out.write("\t\t\t\t\t\t3 : {sorter : 'input_text'},\r\n");
      out.write("\t\t\t\t\t\t4 : {sorter : 'input_text'},\r\n");
      out.write("\t\t\t\t\t\t5 : {sorter : 'input_text'}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t$(\"#categoryDataTable\").on(\t\"click\", \"tr\",\tfunction() {\r\n");
      out.write("\t\t\t\t// 클릭시 row 컬러 변경\r\n");
      out.write("\t\t\t\tvar tr = $(this);\r\n");
      out.write("\t\t\t\tvar td = tr.children();\r\n");
      out.write("\t\t\t\tvar getClickedRow = $(this)\r\n");
      out.write("\t\t\t\t\t\t.index() + 1;\r\n");
      out.write("\t\t\t\tvar bws_seq = $('#twct_bws_seq' + getClickedRow).text();\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t//잘됨.\r\n");
      out.write("\t\t\t\t//$('tr.clicked').removeClass('clicked'); \r\n");
      out.write("\t\t\t\t//tr.addClass('clicked')\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t$(this).addClass('clicked').siblings().removeClass('clicked');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 추가 버튼\r\n");
      out.write("\t\t\t$('#btn_add').click(function() {\r\n");
      out.write("\t\t\t\ttarget_row = 0;\r\n");
      out.write("\t\t\t\tvar rownum = $('#categoryDataTable >tbody tr').length;\r\n");
      out.write("\t\t\t\tvar tbody = $('#categoryDataTable >tbody');\r\n");
      out.write("\t\t\t\t//var row = $('#categoryDataTable >tbody tr');\r\n");
      out.write("\t\t\t\t//var tbody = $('<tbody>');\r\n");
      out.write("\t\t\t\tvar row = $('<tr id=\"rowid_' + rownum + '\">').addClass('trstyle');\r\n");
      out.write("\t\t\t\tvar cell0 = $('<td style=\"text-align:center\"><i class=\"fas fa-caret-right\" id=\"table_font_' + rownum + '\"></i>')\r\n");
      out.write("\t\t\t\tvar cell1 = $('<td style=\"text-align:center\" id=\"bws_seq_' + i + '\">').text('')\r\n");
      out.write("\t\t\t\tvar cell2 = $('<td><input type=\"text\" class=\"data_text\" id=\"bws_content_' + rownum + '\" value=\"\" style=\"width:100%; border:none\">')\r\n");
      out.write("\t\t\t\tvar cell3 = $('<td><input class=\"data_text\" type=\"text\" id=\"bws_remark_' + rownum + '\" value=\"\" style=\"width:100%;border:none\">')\r\n");
      out.write("\t\t\t\tvar cell4 = $('<td class=\"data_text\" style=\"text-align:center\"><input type=\"checkbox\" value=\"Y\" class=\"data_checkbox\" id=\"checkboxID_' + rownum + '\" checked></td>')\r\n");
      out.write("\t\t\t\tvar cell5 = $('<td><input type=\"text\" class=\"data_text\" id=\"sort_no_' + rownum + '\" value=\"999\" style=\"width:100%; border:none\">')\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(row).append(cell0, cell1, cell2, cell3, cell4, cell5);\r\n");
      out.write("\t\t\t\t$('#categoryDataTable >tbody:last').append(row);\r\n");
      out.write("\t\t\t\t//$(tbody).append(row);\r\n");
      out.write("\t\t\t\t//$(\"#categoryDataTable\").append(tbody);\r\n");
      out.write("\t\t\t\t//alert(rownum)\r\n");
      out.write("\t\t\t\ttarget_row = rownum;\r\n");
      out.write("\t\t\t\tchangeFlag(\"I\")\r\n");
      out.write("\t\t\t\t$('#bws_content_' + rownum).focus();\r\n");
      out.write("\t\t\t\t//$('#categoryDataTable >tbody tr').addClass('clicked').siblings().removeClass('clicked');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t// 저장 버튼\r\n");
      out.write("\t\t\t$('#btn_save').click(function() {\r\n");
      out.write("\t\t\t\t//var table = document.getElementById('categoryDataTable')\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#save_check_Title').text('저장 확인')\r\n");
      out.write("\t\t\t\t$('#save_check_Body').html('해당 내역을 저장하시겠습니까?')\r\n");
      out.write("\t\t\t\t$('#SaveCheckModal').modal('show')\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#btn_savecheck_yes').click(function() {\r\n");
      out.write("\t\t\t\tvar indexcnt = $('#categoryDataTable tbody tr').length\r\n");
      out.write("\t\t\t\tvar sendarry = new Array();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (row = 0; row < indexcnt; row++) {\r\n");
      out.write("\t\t\t\t\tvar rowdata = new Object();\r\n");
      out.write("\t\t\t\t\tvar status = $('#table_font_' + row).attr('class')\r\n");
      out.write("\t\t\t\t\t//fas fa-caret-right : 변화 없음\r\n");
      out.write("\t\t\t\t\t//fas fa-pen : 수정\r\n");
      out.write("\t\t\t\t\t//fas fa-plus : 추가\r\n");
      out.write("\t\t\t\t\t//fas fa-cut : 삭제\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\tvar bws_seq\r\n");
      out.write("\t\t\t\t\tvar bws_content\r\n");
      out.write("\t\t\t\t\tvar remark\r\n");
      out.write("\t\t\t\t\tvar use_yn\r\n");
      out.write("\t\t\t\t\tvar sort_no\r\n");
      out.write("\t\t\t\t\tvar status\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\trowdata.bws_seq = $('#bws_seq_' + row).text()\r\n");
      out.write("\t\t\t\t\trowdata.bws_content = $('#bws_content_' + row).val()\r\n");
      out.write("\t\t\t\t\trowdata.remark = $('#bws_remark_' + row).val()\r\n");
      out.write("\t\t\t\t\trowdata.sort_no = $('#sort_no_' + row).val()\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($('#checkboxID_' + row).is(\":checked\")) {\r\n");
      out.write("\t\t\t\t\t\trowdata.use_yn = 'Y'\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\trowdata.use_yn = 'N'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (status == 'fas fa-pen') {\r\n");
      out.write("\t\t\t\t\t\trowdata.status = 'U'\r\n");
      out.write("\t\t\t\t\t} else if (status == 'fas fa-plus') {\r\n");
      out.write("\t\t\t\t\t\trowdata.status = 'I'\r\n");
      out.write("\t\t\t\t\t\tif (!rowdata.bws_content) {\r\n");
      out.write("\t\t\t\t\t\t\t$('#save_info_Title').text('저장 실패')\r\n");
      out.write("\t\t\t\t\t\t\t$('#save_info_Body').html('신규 내역 저장시 반드시 Subject를 입력해 주십시오!')\r\n");
      out.write("\t\t\t\t\t\t\t$('#SaveInfoModal').modal('show')\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t} else if (status == 'fas fa-cut') {\r\n");
      out.write("\t\t\t\t\t\trowdata.status = 'D'\r\n");
      out.write("\t\t\t\t\t\tif (!rowdata.bws_seq) {continue;}\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tcontinue;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsendarry.push(rowdata);\r\n");
      out.write("\t\t\t\t\t//var json = JSON.parse(\"{bws_seq:}\" )\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (!sendarry || sendarry.length == 0) { \r\n");
      out.write("\t\t\t\t\t$('#save_info_Title').text('저장 확인')\r\n");
      out.write("\t\t\t\t\t$('#save_info_Body').html('변경된 내역이 없습니다!')\r\n");
      out.write("\t\t\t\t\t$('#SaveInfoModal').modal('show')\r\n");
      out.write("\t\t\t\t\treturn; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(JSON.stringify(sendarry))\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("biz/saveWeeklySubjectData',\r\n");
      out.write("\t\t\t\t\tcontentType:'application/json',\r\n");
      out.write("\t\t\t\t\t//traditional:true, // 배열 및 리스트로 값을 넘기기 위해서는 꼭 선언되어야함.\r\n");
      out.write("\t\t\t\t\tdata:JSON.stringify(sendarry),\r\n");
      out.write("\t\t\t\t\t//data: {'action_data':sendarry},\r\n");
      out.write("\t\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t//alert('success')\r\n");
      out.write("\t\t\t\t\t\t//alert(result);\r\n");
      out.write("\t\t\t\t\t\tsearchAllSubject();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t// 삭제 버튼\r\n");
      out.write("\t\t\t$('#btn_delete').click(function() {\r\n");
      out.write("\t\t\t\ttarget_row = 0;\r\n");
      out.write("\t\t\t\t//var rownum = $('#categoryDataTable').closest('tr').prevAll().length;\r\n");
      out.write("\t\t\t\t//var rownum = $('#categoryDataTable tbody> tr .trstyle clicked').attr('id');\r\n");
      out.write("\t\t\t\t//var id = $(\"#categoryDataTable\").closest('tr').find(\".id\").html();\r\n");
      out.write("\t\t\t\t//$('table > tbody > tr.highlight');\r\n");
      out.write("\t\t\t\tvar getobject = $('#categoryDataTable > tbody > tr.trstyle.clicked');\r\n");
      out.write("\t\t\t\tvar clicked = getobject.attr('id');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (!clicked) {\r\n");
      out.write("\t\t\t\t\talert('먼저 내역을 선택해주세요!')\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar index = getobject.attr('id').substring(6)\r\n");
      out.write("\t\t\t\tvar id = '#bws_content_' + index\r\n");
      out.write("\t\t\t\tvar seq = $('#bws_seq_' + index).text()\r\n");
      out.write("\t\t\t\tvar bws_content = $(id).val();\r\n");
      out.write("\t\t\t\ttarget_row = index;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (!seq) {\r\n");
      out.write("\t\t\t\t\tvar table = document.getElementById('categoryDataTable')\r\n");
      out.write("\t\t\t\t\tchangeFlag('D')\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#info_Title').text('내역 삭제 확인')\r\n");
      out.write("\t\t\t\t$('#info_Body').html('해당 내역을 삭제하시겠습니까?<br/>&nbsp;<br/>&nbsp; - Subject : ' + bws_content)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#InfoModal').modal('show')\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 데이터 변경시 상태값 변경하기\r\n");
      out.write("\t\t\t$(document).on('click', '.data_checkbox', function(e) {\r\n");
      out.write("\t\t\t\t//alert(JSON.stringify(e))\r\n");
      out.write("\t\t\t\t//alert($(e.target).attr(\"id\"))\r\n");
      out.write("\t\t\t\t//$('#table_font_0').class(\"fas fa-pen\")\r\n");
      out.write("\t\t\t\t//$('#table_font_0').removeClass();\r\n");
      out.write("\t\t\t\t//$('#table_font_0').addClass(\"fas fa-pen\")\r\n");
      out.write("\t\t\t\t//$('#table_font_0').attr('class', 'fas fa-pen');\r\n");
      out.write("\t\t\t\t//$('#table_font_0').toggleClass('fas fa-pen');\r\n");
      out.write("\t\t\t\t//alert('eee')\r\n");
      out.write("\t\t\t\t//var no = td.eq(0).text();\r\n");
      out.write("\t\t\t\tvar rownum = $(this).closest('tr').prevAll().length;\r\n");
      out.write("\t\t\t\t//$('#table_font_' + rownum).attr('class', 'fas fa-pen');\r\n");
      out.write("\t\t\t\ttarget_row = rownum;\r\n");
      out.write("\t\t\t\tchangeFlag('U')\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).on('keydown', '.data_text', function(e) {\r\n");
      out.write("\t\t\t\tvar rownum = $(this).closest('tr').prevAll().length;\r\n");
      out.write("\t\t\t\ttarget_row = rownum;\r\n");
      out.write("\t\t\t\tchangeFlag('U')\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("root");
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/biz/weeklySubjectRgst.jsp(5,0) '${pageContext.request.contextPath }/'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }/",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("mainpath");
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/biz/weeklySubjectRgst.jsp(6,0) '${pageContext.request.contextPath }/static/main/'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }/static/main/",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(89,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/include/main_sidebar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/biz/weeklySubjectRgst.jsp(98,4) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/include/top_bar.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
